/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq;


import cow.infrastructures.jooq.tables.CaseConfig;
import cow.infrastructures.jooq.tables.CaseDetail;
import cow.infrastructures.jooq.tables.CaseGroup;
import cow.infrastructures.jooq.tables.CaseResult;
import cow.infrastructures.jooq.tables.FlywaySchemaHistory;
import cow.infrastructures.jooq.tables.TestConfig;
import cow.infrastructures.jooq.tables.UserAccount;
import cow.infrastructures.jooq.tables.UserDefineParam;
import cow.infrastructures.jooq.tables.records.CaseConfigRecord;
import cow.infrastructures.jooq.tables.records.CaseDetailRecord;
import cow.infrastructures.jooq.tables.records.CaseGroupRecord;
import cow.infrastructures.jooq.tables.records.CaseResultRecord;
import cow.infrastructures.jooq.tables.records.FlywaySchemaHistoryRecord;
import cow.infrastructures.jooq.tables.records.TestConfigRecord;
import cow.infrastructures.jooq.tables.records.UserAccountRecord;
import cow.infrastructures.jooq.tables.records.UserDefineParamRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * cow.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CaseConfigRecord> KEY_CASE_CONFIG_PRIMARY = Internal.createUniqueKey(CaseConfig.CASE_CONFIG, DSL.name("KEY_case_config_PRIMARY"), new TableField[] { CaseConfig.CASE_CONFIG.ID }, true);
    public static final UniqueKey<CaseDetailRecord> KEY_CASE_DETAIL_PRIMARY = Internal.createUniqueKey(CaseDetail.CASE_DETAIL, DSL.name("KEY_case_detail_PRIMARY"), new TableField[] { CaseDetail.CASE_DETAIL.ID }, true);
    public static final UniqueKey<CaseGroupRecord> KEY_CASE_GROUP_PRIMARY = Internal.createUniqueKey(CaseGroup.CASE_GROUP, DSL.name("KEY_case_group_PRIMARY"), new TableField[] { CaseGroup.CASE_GROUP.ID }, true);
    public static final UniqueKey<CaseResultRecord> KEY_CASE_RESULT_PRIMARY = Internal.createUniqueKey(CaseResult.CASE_RESULT, DSL.name("KEY_case_result_PRIMARY"), new TableField[] { CaseResult.CASE_RESULT.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TestConfigRecord> KEY_TEST_CONFIG_PRIMARY = Internal.createUniqueKey(TestConfig.TEST_CONFIG, DSL.name("KEY_test_config_PRIMARY"), new TableField[] { TestConfig.TEST_CONFIG.ID }, true);
    public static final UniqueKey<UserAccountRecord> KEY_USER_ACCOUNT_MERP_ACCOUNT_UN = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("KEY_user_account_merp_account_UN"), new TableField[] { UserAccount.USER_ACCOUNT.ACCOUNT }, true);
    public static final UniqueKey<UserAccountRecord> KEY_USER_ACCOUNT_PRIMARY = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("KEY_user_account_PRIMARY"), new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final UniqueKey<UserDefineParamRecord> KEY_USER_DEFINE_PARAM_PRIMARY = Internal.createUniqueKey(UserDefineParam.USER_DEFINE_PARAM, DSL.name("KEY_user_define_param_PRIMARY"), new TableField[] { UserDefineParam.USER_DEFINE_PARAM.ID }, true);
}
