/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq;


import cow.infrastructures.jooq.tables.CaseDetail;
import cow.infrastructures.jooq.tables.CaseGroup;
import cow.infrastructures.jooq.tables.CaseResult;
import cow.infrastructures.jooq.tables.FlywaySchemaHistory;
import cow.infrastructures.jooq.tables.TestConfig;
import cow.infrastructures.jooq.tables.UserAccount;
import cow.infrastructures.jooq.tables.UserDefineParam;


/**
 * Convenience access to all tables in cow.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cow.case_detail</code>.
     */
    public static final CaseDetail CASE_DETAIL = CaseDetail.CASE_DETAIL;

    /**
     * The table <code>cow.case_group</code>.
     */
    public static final CaseGroup CASE_GROUP = CaseGroup.CASE_GROUP;

    /**
     * The table <code>cow.case_result</code>.
     */
    public static final CaseResult CASE_RESULT = CaseResult.CASE_RESULT;

    /**
     * The table <code>cow.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>cow.test_config</code>.
     */
    public static final TestConfig TEST_CONFIG = TestConfig.TEST_CONFIG;

    /**
     * The table <code>cow.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>cow.user_define_param</code>.
     */
    public static final UserDefineParam USER_DEFINE_PARAM = UserDefineParam.USER_DEFINE_PARAM;
}
