/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq.tables.records;


import cow.infrastructures.jooq.tables.CaseDetail;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseDetailRecord extends UpdatableRecordImpl<CaseDetailRecord> implements Record17<Integer, String, String, String, String, String, String, String, String, Integer, Integer, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cow.case_detail.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cow.case_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cow.case_detail.url</code>. url
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cow.case_detail.url</code>. url
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cow.case_detail.path</code>. 请求路径
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cow.case_detail.path</code>. 请求路径
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cow.case_detail.header</code>. 请求头
     */
    public void setHeader(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cow.case_detail.header</code>. 请求头
     */
    public String getHeader() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cow.case_detail.method</code>. 请求方式
     */
    public void setMethod(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cow.case_detail.method</code>. 请求方式
     */
    public String getMethod() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cow.case_detail.data</code>. 请求报文
     */
    public void setData(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cow.case_detail.data</code>. 请求报文
     */
    public String getData() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cow.case_detail.assertions</code>. 断言
     */
    public void setAssertions(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cow.case_detail.assertions</code>. 断言
     */
    public String getAssertions() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cow.case_detail.extract</code>. 提取参数
     */
    public void setExtract(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cow.case_detail.extract</code>. 提取参数
     */
    public String getExtract() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cow.case_detail.description</code>. 描述
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cow.case_detail.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cow.case_detail.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>cow.case_detail.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>cow.case_detail.sort</code>. 执行顺序
     */
    public void setSort(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>cow.case_detail.sort</code>. 执行顺序
     */
    public Integer getSort() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>cow.case_detail.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public void setDeleteFlag(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>cow.case_detail.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public Integer getDeleteFlag() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>cow.case_detail.record_date</code>. 创建日期
     */
    public void setRecordDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>cow.case_detail.record_date</code>. 创建日期
     */
    public LocalDate getRecordDate() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>cow.case_detail.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>cow.case_detail.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>cow.case_detail.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cow.case_detail.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cow.case_detail.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>cow.case_detail.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>cow.case_detail.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>cow.case_detail.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, Integer, Integer, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, Integer, Integer, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CaseDetail.CASE_DETAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return CaseDetail.CASE_DETAIL.URL;
    }

    @Override
    public Field<String> field3() {
        return CaseDetail.CASE_DETAIL.PATH;
    }

    @Override
    public Field<String> field4() {
        return CaseDetail.CASE_DETAIL.HEADER;
    }

    @Override
    public Field<String> field5() {
        return CaseDetail.CASE_DETAIL.METHOD;
    }

    @Override
    public Field<String> field6() {
        return CaseDetail.CASE_DETAIL.DATA;
    }

    @Override
    public Field<String> field7() {
        return CaseDetail.CASE_DETAIL.ASSERTIONS;
    }

    @Override
    public Field<String> field8() {
        return CaseDetail.CASE_DETAIL.EXTRACT;
    }

    @Override
    public Field<String> field9() {
        return CaseDetail.CASE_DETAIL.DESCRIPTION;
    }

    @Override
    public Field<Integer> field10() {
        return CaseDetail.CASE_DETAIL.GROUP_ID;
    }

    @Override
    public Field<Integer> field11() {
        return CaseDetail.CASE_DETAIL.SORT;
    }

    @Override
    public Field<Integer> field12() {
        return CaseDetail.CASE_DETAIL.DELETE_FLAG;
    }

    @Override
    public Field<LocalDate> field13() {
        return CaseDetail.CASE_DETAIL.RECORD_DATE;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return CaseDetail.CASE_DETAIL.CREATED_AT;
    }

    @Override
    public Field<String> field15() {
        return CaseDetail.CASE_DETAIL.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return CaseDetail.CASE_DETAIL.UPDATED_AT;
    }

    @Override
    public Field<String> field17() {
        return CaseDetail.CASE_DETAIL.UPDATED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getPath();
    }

    @Override
    public String component4() {
        return getHeader();
    }

    @Override
    public String component5() {
        return getMethod();
    }

    @Override
    public String component6() {
        return getData();
    }

    @Override
    public String component7() {
        return getAssertions();
    }

    @Override
    public String component8() {
        return getExtract();
    }

    @Override
    public String component9() {
        return getDescription();
    }

    @Override
    public Integer component10() {
        return getGroupId();
    }

    @Override
    public Integer component11() {
        return getSort();
    }

    @Override
    public Integer component12() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate component13() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime component14() {
        return getCreatedAt();
    }

    @Override
    public String component15() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component16() {
        return getUpdatedAt();
    }

    @Override
    public String component17() {
        return getUpdatedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getPath();
    }

    @Override
    public String value4() {
        return getHeader();
    }

    @Override
    public String value5() {
        return getMethod();
    }

    @Override
    public String value6() {
        return getData();
    }

    @Override
    public String value7() {
        return getAssertions();
    }

    @Override
    public String value8() {
        return getExtract();
    }

    @Override
    public String value9() {
        return getDescription();
    }

    @Override
    public Integer value10() {
        return getGroupId();
    }

    @Override
    public Integer value11() {
        return getSort();
    }

    @Override
    public Integer value12() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate value13() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime value14() {
        return getCreatedAt();
    }

    @Override
    public String value15() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value16() {
        return getUpdatedAt();
    }

    @Override
    public String value17() {
        return getUpdatedBy();
    }

    @Override
    public CaseDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CaseDetailRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public CaseDetailRecord value3(String value) {
        setPath(value);
        return this;
    }

    @Override
    public CaseDetailRecord value4(String value) {
        setHeader(value);
        return this;
    }

    @Override
    public CaseDetailRecord value5(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public CaseDetailRecord value6(String value) {
        setData(value);
        return this;
    }

    @Override
    public CaseDetailRecord value7(String value) {
        setAssertions(value);
        return this;
    }

    @Override
    public CaseDetailRecord value8(String value) {
        setExtract(value);
        return this;
    }

    @Override
    public CaseDetailRecord value9(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CaseDetailRecord value10(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public CaseDetailRecord value11(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public CaseDetailRecord value12(Integer value) {
        setDeleteFlag(value);
        return this;
    }

    @Override
    public CaseDetailRecord value13(LocalDate value) {
        setRecordDate(value);
        return this;
    }

    @Override
    public CaseDetailRecord value14(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CaseDetailRecord value15(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CaseDetailRecord value16(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CaseDetailRecord value17(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public CaseDetailRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Integer value10, Integer value11, Integer value12, LocalDate value13, LocalDateTime value14, String value15, LocalDateTime value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseDetailRecord
     */
    public CaseDetailRecord() {
        super(CaseDetail.CASE_DETAIL);
    }

    /**
     * Create a detached, initialised CaseDetailRecord
     */
    public CaseDetailRecord(Integer id, String url, String path, String header, String method, String data, String assertions, String extract, String description, Integer groupId, Integer sort, Integer deleteFlag, LocalDate recordDate, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(CaseDetail.CASE_DETAIL);

        setId(id);
        setUrl(url);
        setPath(path);
        setHeader(header);
        setMethod(method);
        setData(data);
        setAssertions(assertions);
        setExtract(extract);
        setDescription(description);
        setGroupId(groupId);
        setSort(sort);
        setDeleteFlag(deleteFlag);
        setRecordDate(recordDate);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }
}
