/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq.tables.records;


import cow.infrastructures.jooq.tables.CaseResult;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseResultRecord extends UpdatableRecordImpl<CaseResultRecord> implements Record18<Integer, Integer, Integer, String, String, String, String, String, Integer, Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cow.case_result.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cow.case_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cow.case_result.case_group_id</code>.
     */
    public void setCaseGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cow.case_result.case_group_id</code>.
     */
    public Integer getCaseGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cow.case_result.case_id</code>.
     */
    public void setCaseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cow.case_result.case_id</code>.
     */
    public Integer getCaseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cow.case_result.url</code>. url
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cow.case_result.url</code>. url
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cow.case_result.path</code>. 请求路径
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cow.case_result.path</code>. 请求路径
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cow.case_result.header</code>. 请求头
     */
    public void setHeader(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cow.case_result.header</code>. 请求头
     */
    public String getHeader() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cow.case_result.method</code>. 请求方式
     */
    public void setMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cow.case_result.method</code>. 请求方式
     */
    public String getMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cow.case_result.data</code>. 请求报文
     */
    public void setData(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cow.case_result.data</code>. 请求报文
     */
    public String getData() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cow.case_result.responce_result</code>. 请求结果
     */
    public void setResponceResult(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>cow.case_result.responce_result</code>. 请求结果
     */
    public Integer getResponceResult() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>cow.case_result.assert_result</code>. 断言结果
     */
    public void setAssertResult(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>cow.case_result.assert_result</code>. 断言结果
     */
    public Integer getAssertResult() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>cow.case_result.extract_result</code>. 提取结果
     */
    public void setExtractResult(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>cow.case_result.extract_result</code>. 提取结果
     */
    public Integer getExtractResult() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>cow.case_result.user_define_parameters</code>.
     */
    public void setUserDefineParameters(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cow.case_result.user_define_parameters</code>.
     */
    public String getUserDefineParameters() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cow.case_result.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public void setDeleteFlag(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>cow.case_result.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public Integer getDeleteFlag() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>cow.case_result.record_date</code>. 创建日期
     */
    public void setRecordDate(LocalDate value) {
        set(13, value);
    }

    /**
     * Getter for <code>cow.case_result.record_date</code>. 创建日期
     */
    public LocalDate getRecordDate() {
        return (LocalDate) get(13);
    }

    /**
     * Setter for <code>cow.case_result.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>cow.case_result.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>cow.case_result.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>cow.case_result.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>cow.case_result.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>cow.case_result.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>cow.case_result.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>cow.case_result.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Integer, Integer, Integer, String, String, String, String, String, Integer, Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Integer, Integer, Integer, String, String, String, String, String, Integer, Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CaseResult.CASE_RESULT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return CaseResult.CASE_RESULT.CASE_GROUP_ID;
    }

    @Override
    public Field<Integer> field3() {
        return CaseResult.CASE_RESULT.CASE_ID;
    }

    @Override
    public Field<String> field4() {
        return CaseResult.CASE_RESULT.URL;
    }

    @Override
    public Field<String> field5() {
        return CaseResult.CASE_RESULT.PATH;
    }

    @Override
    public Field<String> field6() {
        return CaseResult.CASE_RESULT.HEADER;
    }

    @Override
    public Field<String> field7() {
        return CaseResult.CASE_RESULT.METHOD;
    }

    @Override
    public Field<String> field8() {
        return CaseResult.CASE_RESULT.DATA;
    }

    @Override
    public Field<Integer> field9() {
        return CaseResult.CASE_RESULT.RESPONCE_RESULT;
    }

    @Override
    public Field<Integer> field10() {
        return CaseResult.CASE_RESULT.ASSERT_RESULT;
    }

    @Override
    public Field<Integer> field11() {
        return CaseResult.CASE_RESULT.EXTRACT_RESULT;
    }

    @Override
    public Field<String> field12() {
        return CaseResult.CASE_RESULT.USER_DEFINE_PARAMETERS;
    }

    @Override
    public Field<Integer> field13() {
        return CaseResult.CASE_RESULT.DELETE_FLAG;
    }

    @Override
    public Field<LocalDate> field14() {
        return CaseResult.CASE_RESULT.RECORD_DATE;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return CaseResult.CASE_RESULT.CREATED_AT;
    }

    @Override
    public Field<String> field16() {
        return CaseResult.CASE_RESULT.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return CaseResult.CASE_RESULT.UPDATED_AT;
    }

    @Override
    public Field<String> field18() {
        return CaseResult.CASE_RESULT.UPDATED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCaseGroupId();
    }

    @Override
    public Integer component3() {
        return getCaseId();
    }

    @Override
    public String component4() {
        return getUrl();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public String component6() {
        return getHeader();
    }

    @Override
    public String component7() {
        return getMethod();
    }

    @Override
    public String component8() {
        return getData();
    }

    @Override
    public Integer component9() {
        return getResponceResult();
    }

    @Override
    public Integer component10() {
        return getAssertResult();
    }

    @Override
    public Integer component11() {
        return getExtractResult();
    }

    @Override
    public String component12() {
        return getUserDefineParameters();
    }

    @Override
    public Integer component13() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate component14() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime component15() {
        return getCreatedAt();
    }

    @Override
    public String component16() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component17() {
        return getUpdatedAt();
    }

    @Override
    public String component18() {
        return getUpdatedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCaseGroupId();
    }

    @Override
    public Integer value3() {
        return getCaseId();
    }

    @Override
    public String value4() {
        return getUrl();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public String value6() {
        return getHeader();
    }

    @Override
    public String value7() {
        return getMethod();
    }

    @Override
    public String value8() {
        return getData();
    }

    @Override
    public Integer value9() {
        return getResponceResult();
    }

    @Override
    public Integer value10() {
        return getAssertResult();
    }

    @Override
    public Integer value11() {
        return getExtractResult();
    }

    @Override
    public String value12() {
        return getUserDefineParameters();
    }

    @Override
    public Integer value13() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate value14() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime value15() {
        return getCreatedAt();
    }

    @Override
    public String value16() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value17() {
        return getUpdatedAt();
    }

    @Override
    public String value18() {
        return getUpdatedBy();
    }

    @Override
    public CaseResultRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CaseResultRecord value2(Integer value) {
        setCaseGroupId(value);
        return this;
    }

    @Override
    public CaseResultRecord value3(Integer value) {
        setCaseId(value);
        return this;
    }

    @Override
    public CaseResultRecord value4(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public CaseResultRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public CaseResultRecord value6(String value) {
        setHeader(value);
        return this;
    }

    @Override
    public CaseResultRecord value7(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public CaseResultRecord value8(String value) {
        setData(value);
        return this;
    }

    @Override
    public CaseResultRecord value9(Integer value) {
        setResponceResult(value);
        return this;
    }

    @Override
    public CaseResultRecord value10(Integer value) {
        setAssertResult(value);
        return this;
    }

    @Override
    public CaseResultRecord value11(Integer value) {
        setExtractResult(value);
        return this;
    }

    @Override
    public CaseResultRecord value12(String value) {
        setUserDefineParameters(value);
        return this;
    }

    @Override
    public CaseResultRecord value13(Integer value) {
        setDeleteFlag(value);
        return this;
    }

    @Override
    public CaseResultRecord value14(LocalDate value) {
        setRecordDate(value);
        return this;
    }

    @Override
    public CaseResultRecord value15(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CaseResultRecord value16(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CaseResultRecord value17(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CaseResultRecord value18(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public CaseResultRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Integer value10, Integer value11, String value12, Integer value13, LocalDate value14, LocalDateTime value15, String value16, LocalDateTime value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseResultRecord
     */
    public CaseResultRecord() {
        super(CaseResult.CASE_RESULT);
    }

    /**
     * Create a detached, initialised CaseResultRecord
     */
    public CaseResultRecord(Integer id, Integer caseGroupId, Integer caseId, String url, String path, String header, String method, String data, Integer responceResult, Integer assertResult, Integer extractResult, String userDefineParameters, Integer deleteFlag, LocalDate recordDate, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(CaseResult.CASE_RESULT);

        setId(id);
        setCaseGroupId(caseGroupId);
        setCaseId(caseId);
        setUrl(url);
        setPath(path);
        setHeader(header);
        setMethod(method);
        setData(data);
        setResponceResult(responceResult);
        setAssertResult(assertResult);
        setExtractResult(extractResult);
        setUserDefineParameters(userDefineParameters);
        setDeleteFlag(deleteFlag);
        setRecordDate(recordDate);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }
}
