/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq.tables.records;


import cow.infrastructures.jooq.tables.CaseGroup;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseGroupRecord extends UpdatableRecordImpl<CaseGroupRecord> implements Record8<Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cow.case_group.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cow.case_group.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cow.case_group.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cow.case_group.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cow.case_group.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public void setDeleteFlag(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cow.case_group.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public Integer getDeleteFlag() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cow.case_group.record_date</code>. 创建日期
     */
    public void setRecordDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>cow.case_group.record_date</code>. 创建日期
     */
    public LocalDate getRecordDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>cow.case_group.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cow.case_group.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>cow.case_group.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cow.case_group.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cow.case_group.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>cow.case_group.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>cow.case_group.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cow.case_group.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CaseGroup.CASE_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return CaseGroup.CASE_GROUP.DESCRIPTION;
    }

    @Override
    public Field<Integer> field3() {
        return CaseGroup.CASE_GROUP.DELETE_FLAG;
    }

    @Override
    public Field<LocalDate> field4() {
        return CaseGroup.CASE_GROUP.RECORD_DATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CaseGroup.CASE_GROUP.CREATED_AT;
    }

    @Override
    public Field<String> field6() {
        return CaseGroup.CASE_GROUP.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return CaseGroup.CASE_GROUP.UPDATED_AT;
    }

    @Override
    public Field<String> field8() {
        return CaseGroup.CASE_GROUP.UPDATED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Integer component3() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate component4() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public String component6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public String component8() {
        return getUpdatedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public Integer value3() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate value4() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public String value6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public String value8() {
        return getUpdatedBy();
    }

    @Override
    public CaseGroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CaseGroupRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CaseGroupRecord value3(Integer value) {
        setDeleteFlag(value);
        return this;
    }

    @Override
    public CaseGroupRecord value4(LocalDate value) {
        setRecordDate(value);
        return this;
    }

    @Override
    public CaseGroupRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CaseGroupRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CaseGroupRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CaseGroupRecord value8(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public CaseGroupRecord values(Integer value1, String value2, Integer value3, LocalDate value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseGroupRecord
     */
    public CaseGroupRecord() {
        super(CaseGroup.CASE_GROUP);
    }

    /**
     * Create a detached, initialised CaseGroupRecord
     */
    public CaseGroupRecord(Integer id, String description, Integer deleteFlag, LocalDate recordDate, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(CaseGroup.CASE_GROUP);

        setId(id);
        setDescription(description);
        setDeleteFlag(deleteFlag);
        setRecordDate(recordDate);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }
}
