/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq.tables.records;


import cow.infrastructures.jooq.tables.UserDefineParam;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefineParamRecord extends UpdatableRecordImpl<UserDefineParamRecord> implements Record9<Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cow.user_define_param.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cow.user_define_param.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cow.user_define_param.case_group_id</code>.
     */
    public void setCaseGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cow.user_define_param.case_group_id</code>.
     */
    public Integer getCaseGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cow.user_define_param.user_define_parameters</code>.
     */
    public void setUserDefineParameters(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cow.user_define_param.user_define_parameters</code>.
     */
    public String getUserDefineParameters() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cow.user_define_param.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public void setDeleteFlag(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>cow.user_define_param.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public Integer getDeleteFlag() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>cow.user_define_param.record_date</code>. 创建日期
     */
    public void setRecordDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>cow.user_define_param.record_date</code>. 创建日期
     */
    public LocalDate getRecordDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>cow.user_define_param.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cow.user_define_param.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>cow.user_define_param.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cow.user_define_param.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cow.user_define_param.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>cow.user_define_param.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>cow.user_define_param.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cow.user_define_param.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserDefineParam.USER_DEFINE_PARAM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserDefineParam.USER_DEFINE_PARAM.CASE_GROUP_ID;
    }

    @Override
    public Field<String> field3() {
        return UserDefineParam.USER_DEFINE_PARAM.USER_DEFINE_PARAMETERS;
    }

    @Override
    public Field<Integer> field4() {
        return UserDefineParam.USER_DEFINE_PARAM.DELETE_FLAG;
    }

    @Override
    public Field<LocalDate> field5() {
        return UserDefineParam.USER_DEFINE_PARAM.RECORD_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserDefineParam.USER_DEFINE_PARAM.CREATED_AT;
    }

    @Override
    public Field<String> field7() {
        return UserDefineParam.USER_DEFINE_PARAM.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserDefineParam.USER_DEFINE_PARAM.UPDATED_AT;
    }

    @Override
    public Field<String> field9() {
        return UserDefineParam.USER_DEFINE_PARAM.UPDATED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCaseGroupId();
    }

    @Override
    public String component3() {
        return getUserDefineParameters();
    }

    @Override
    public Integer component4() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate component5() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public String component7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public String component9() {
        return getUpdatedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCaseGroupId();
    }

    @Override
    public String value3() {
        return getUserDefineParameters();
    }

    @Override
    public Integer value4() {
        return getDeleteFlag();
    }

    @Override
    public LocalDate value5() {
        return getRecordDate();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public String value7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public String value9() {
        return getUpdatedBy();
    }

    @Override
    public UserDefineParamRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value2(Integer value) {
        setCaseGroupId(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value3(String value) {
        setUserDefineParameters(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value4(Integer value) {
        setDeleteFlag(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value5(LocalDate value) {
        setRecordDate(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value7(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value9(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public UserDefineParamRecord values(Integer value1, Integer value2, String value3, Integer value4, LocalDate value5, LocalDateTime value6, String value7, LocalDateTime value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDefineParamRecord
     */
    public UserDefineParamRecord() {
        super(UserDefineParam.USER_DEFINE_PARAM);
    }

    /**
     * Create a detached, initialised UserDefineParamRecord
     */
    public UserDefineParamRecord(Integer id, Integer caseGroupId, String userDefineParameters, Integer deleteFlag, LocalDate recordDate, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(UserDefineParam.USER_DEFINE_PARAM);

        setId(id);
        setCaseGroupId(caseGroupId);
        setUserDefineParameters(userDefineParameters);
        setDeleteFlag(deleteFlag);
        setRecordDate(recordDate);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }
}
