/*
 * This file is generated by jOOQ.
 */
package cow.infrastructures.jooq.tables;


import cow.infrastructures.jooq.Cow;
import cow.infrastructures.jooq.Keys;
import cow.infrastructures.jooq.tables.records.CaseConfigRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseConfig extends TableImpl<CaseConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cow.case_config</code>
     */
    public static final CaseConfig CASE_CONFIG = new CaseConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CaseConfigRecord> getRecordType() {
        return CaseConfigRecord.class;
    }

    /**
     * The column <code>cow.case_config.id</code>.
     */
    public final TableField<CaseConfigRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cow.case_config.url</code>.
     */
    public final TableField<CaseConfigRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>cow.case_config.headers</code>.
     */
    public final TableField<CaseConfigRecord, String> HEADERS = createField(DSL.name("headers"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>cow.case_config.delete_flag</code>. 删除标志, 1未删除 0已删除
     */
    public final TableField<CaseConfigRecord, Integer> DELETE_FLAG = createField(DSL.name("delete_flag"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "删除标志, 1未删除 0已删除");

    /**
     * The column <code>cow.case_config.record_date</code>. 创建日期
     */
    public final TableField<CaseConfigRecord, LocalDate> RECORD_DATE = createField(DSL.name("record_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.inline("1000-01-01", SQLDataType.LOCALDATE)), this, "创建日期");

    /**
     * The column <code>cow.case_config.created_at</code>. 创建时间
     */
    public final TableField<CaseConfigRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>cow.case_config.created_by</code>.
     */
    public final TableField<CaseConfigRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("system", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cow.case_config.updated_at</code>. 更新时间
     */
    public final TableField<CaseConfigRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>cow.case_config.updated_by</code>.
     */
    public final TableField<CaseConfigRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    private CaseConfig(Name alias, Table<CaseConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private CaseConfig(Name alias, Table<CaseConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>cow.case_config</code> table reference
     */
    public CaseConfig(String alias) {
        this(DSL.name(alias), CASE_CONFIG);
    }

    /**
     * Create an aliased <code>cow.case_config</code> table reference
     */
    public CaseConfig(Name alias) {
        this(alias, CASE_CONFIG);
    }

    /**
     * Create a <code>cow.case_config</code> table reference
     */
    public CaseConfig() {
        this(DSL.name("case_config"), null);
    }

    public <O extends Record> CaseConfig(Table<O> child, ForeignKey<O, CaseConfigRecord> key) {
        super(child, key, CASE_CONFIG);
    }

    @Override
    public Schema getSchema() {
        return Cow.COW;
    }

    @Override
    public UniqueKey<CaseConfigRecord> getPrimaryKey() {
        return Keys.KEY_CASE_CONFIG_PRIMARY;
    }

    @Override
    public List<UniqueKey<CaseConfigRecord>> getKeys() {
        return Arrays.<UniqueKey<CaseConfigRecord>>asList(Keys.KEY_CASE_CONFIG_PRIMARY);
    }

    @Override
    public CaseConfig as(String alias) {
        return new CaseConfig(DSL.name(alias), this);
    }

    @Override
    public CaseConfig as(Name alias) {
        return new CaseConfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CaseConfig rename(String name) {
        return new CaseConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CaseConfig rename(Name name) {
        return new CaseConfig(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, Integer, LocalDate, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
